version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /infra
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /frontend-client
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /frontend-admin
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /frontend-marketing
    schedule:
      interval: daily
